// react-traversy/react-task-tracker/src/components/Button.js
import PropTypes from 'prop-types'

const Button = ({color, text, onClick}) => {
    return (     
        <button 
        onClick={onClick} 
        style={{ backgroundColor: color }}
        className='btn'>
            {text}
        </button> 
    )
}

Button.defaultProps = {
    color: 'steelblue'
}

Button.propTypes = {
    text: PropTypes.string,
    color: PropTypes.string,
    onClick: PropTypes.func,
}
export default Button

// vue-traversy/vue-task-tracker/vue-crash-2021/src/components/Button.vue
<template>
    <button @click="onClick()" class="btn" :style="{background: color}">{{text}}</button>
</template>

<script>

export default {
    name: 'Button',
    props: {
       text: String,
       color: String
    },
    methods: {
        onClick() {
            this.$emit('btn-click')
        },
    }
}
</script>
